# kubectl create rolebinding job-reader-rolebinding --role=job-reader --serviceaccount=default:default --dry-run=client -o yaml > ops/k8s/app/job-reader-rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: job-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
