# kubectl create role job-reader --verb=get,list,watch --resource=jobs --dry-run=client -o yaml > ops/k8s/app/job-reader-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: job-reader
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
